2019-03-24 10:54:59,477-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 10:54:59,501-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:54:59,509-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:54:59,517-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone':'18688773422','pwd':'123456'}
2019-03-24 10:55:28,263-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 10:55:28,398-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:55:28,515-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:55:28,610-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone':'18688773422','pwd':'123456'}
2019-03-24 10:55:57,902-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 10:55:58,022-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:55:58,026-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 10:55:58,032-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:55:58,148-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:55:58,152-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 10:55:58,158-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:55:58,260-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:55:58,265-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 10:55:58,276-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone':'18688773422','pwd':'123456'}
2019-03-24 10:55:58,367-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:55:58,371-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 10:58:05,607-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 10:58:05,714-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:58:05,716-ERROR-test_logger.py-测试使用-日志信息:断言错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-24 10:58:05,720-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:58:05,817-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:58:05,820-ERROR-test_logger.py-测试使用-日志信息:断言错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-24 10:58:05,824-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 10:58:05,924-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:58:05,927-ERROR-test_logger.py-测试使用-日志信息:断言错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-24 10:58:05,930-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone':'18688773422','pwd':'123456'}
2019-03-24 10:58:06,026-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 10:58:06,031-ERROR-test_logger.py-测试使用-日志信息:断言错误是：'10001' != '20103'
- 10001
+ 20103

2019-03-24 11:01:11,504-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 11:01:11,622-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 11:01:11,625-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 11:01:11,631-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123456'}
2019-03-24 11:01:11,728-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 11:01:11,731-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 11:01:11,741-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone':'18688773467','pwd':'123356'}
2019-03-24 11:01:11,835-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 11:01:11,839-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 11:01:11,846-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone':'18688773422','pwd':'123456'}
2019-03-24 11:01:11,945-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20103
2019-03-24 11:01:11,949-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20103
2019-03-24 11:02:18,868-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:18,998-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:19,001-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:19,097-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:19,107-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123356'}
2019-03-24 11:02:19,212-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20111
2019-03-24 11:02:19,215-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20111
2019-03-24 11:02:19,226-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone': '18688773422', 'pwd': '123456'}
2019-03-24 11:02:19,336-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是20111
2019-03-24 11:02:19,339-ERROR-test_logger.py-测试使用-日志信息:断言错误是： :: 10001 != 20111
2019-03-24 11:02:40,377-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:40,502-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:40,510-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:40,612-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:40,620-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123356'}
2019-03-24 11:02:40,711-INFO-test_logger.py-测试使用-日志信息:期望结果是：20111，实际结果是20111
2019-03-24 11:02:40,714-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone': '18688773422', 'pwd': '123456'}
2019-03-24 11:02:40,817-INFO-test_logger.py-测试使用-日志信息:期望结果是：20111，实际结果是20111
2019-03-24 11:02:46,905-INFO-test_logger.py-测试使用-日志信息:正在执行第1条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:47,008-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:47,010-INFO-test_logger.py-测试使用-日志信息:正在执行第2条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123456'}
2019-03-24 11:02:47,107-INFO-test_logger.py-测试使用-日志信息:期望结果是：10001，实际结果是10001
2019-03-24 11:02:47,110-INFO-test_logger.py-测试使用-日志信息:正在执行第3条用例，测试数据是：{'mobilephone': '18688773467', 'pwd': '123356'}
2019-03-24 11:02:47,203-INFO-test_logger.py-测试使用-日志信息:期望结果是：20111，实际结果是20111
2019-03-24 11:02:47,206-INFO-test_logger.py-测试使用-日志信息:正在执行第4条用例，测试数据是：{'mobilephone': '18688773422', 'pwd': '123456'}
2019-03-24 11:02:47,302-INFO-test_logger.py-测试使用-日志信息:期望结果是：20111，实际结果是20111
